version: '3'

networks:
  project_net:
    ipam:
      config:
        - subnet: 172.91.0.0/24

services:
  # Permite la generación y exportación de documentos PDF y códigos QR
  exporter:
    image: exporter
    build:
      context: .
      dockerfile: ./DockerFiles/exporter.dockerfile
    restart: always
    ports:
    - "5070:5050"
    volumes: 
    - ./Templates:/usr/src/app/Templates
    env_file:
    - ./variables.env
    networks:
      project_net:
        ipv4_address: 172.91.0.10
    links:
    - assets
  backend_main:
    # Conecta la BDD Mongo con el FRONTEND
    image: backend_main
    build:
      context: .
      dockerfile: ./DockerFiles/backend_main.dockerfile
    restart: always
    ports:
    - "5071:5050"
    env_file:
    - ./variables.env
    environment:
      mongo_bdd: ia
      mongo_bdd_server: mongo_ia_data
    volumes: 
    - ./logs/logs_backend_main.txt:/usr/src/app/logs.txt
    networks:
      project_net:
        ipv4_address: 172.91.0.11
    links:
    - mongo_ia_data
  data_analizer:
    # IA que clasifica Tweets
    image: data_analizer
    build:
      context: .
      dockerfile: ./DockerFiles/data_analizer.dockerfile
    env_file:
    - ./variables.env
    environment:
      mongo_bdd: ia
      mongo_bdd_server: mongo_ia_data
    volumes: 
    - ./logs/logs_data_analizer.txt:/usr/src/app/logs.txt
    networks:
      project_net:
        ipv4_address: 172.91.0.12
    links:
    - mongo_ia_data
  mongo_ia_data:
    # Capa de Persistencia que almacena datos
    image: mongo:latest
    restart: always
    volumes: 
    - ./db/mongo_ia_data:/data/db
    env_file:
    - ./variables.env
    networks:
      project_net:
        ipv4_address: 172.91.0.13
  mongo_ia_data_express:
    # Interfaz de administracion de MongoDB
    image: mongo-express:latest
    restart: always
    ports:
    - "9071:8081"
    env_file:
    - ./variables.env
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo_ia_data
    networks:
      project_net:
        ipv4_address: 172.91.0.14
    links:
    - mongo_ia_data
  assets:
    # Libreria de documentos, imagenes y videos
    ports:
    - "9999:80"
    image: httpd:latest
    restart: always
    volumes:
    - ./assets:/usr/local/apache2/htdocs/files
    - ./httpd_conf/httpd.conf:/usr/local/apache2/conf/httpd.conf
    networks:
      project_net:
        ipv4_address: 172.91.0.15